package org.mightypig.wurm.mediumanvil;

import com.wurmonline.server.Features;
import com.wurmonline.server.MiscConstants;
import com.wurmonline.server.items.*;
import static com.wurmonline.server.items.CreationEntryCreator.*;

import org.gotti.wurmunlimited.modloader.interfaces.ItemTemplatesCreatedListener;
import org.gotti.wurmunlimited.modloader.interfaces.Versioned;
import org.gotti.wurmunlimited.modloader.interfaces.WurmServerMod;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

public class Mediumanvil implements WurmServerMod, ItemTemplatesCreatedListener, Versioned {
    public static final Logger logger = Logger.getLogger(Mediumanvil.class.getName());
    @Override
    public void onItemTemplatesCreated() {
        options.registerIds();
        try {
            ItemTemplateCreator.createItemTemplate(options.MediumanvilId, 3,"anvil", "anvils", "almost full", "somewhat occupied", "half-full", "emptyish",
                    "An anvil that acts like a small and large combined in one.", new short[]{108, 38, 22, 44, 157, 51}, (short) 791,
                    (short) 1, 0, 3024000L, 10, 10, 10, -10, MiscConstants.EMPTY_BYTE_PRIMITIVE_ARRAY,
                    "model.tool.anvil.large.", 5.0F, 5000, (byte) 11, 10000, true, -1);
        } catch (IOException e) {
            Mediumanvil.logger.log(Level.SEVERE, "Failed while creating item template for Medium Anvil", e);
        }
        addSimpleEntry();
    }

    @Override
    public String getVersion() {
        return "1.0";
    }

    public static void addSimpleEntry() {
        if (Features.Feature.METALLIC_ITEMS.isEnabled()) {
            // small anvil recipes
            createMetallicEntries(10015, 63, 46, options.MediumanvilId, false, true, 0.0F, false, false, CreationCategories.TOOLS);
            createMetallicEntries(10015, 62, 46, options.MediumanvilId, false, true, 0.0F, false, false, CreationCategories.TOOLS);
            createMetallicEntries(10010, options.MediumanvilId, 46, 147, false, true, 0.0F, false, false, CreationCategories.BLADES);
            createMetallicEntries(10011, options.MediumanvilId, 46, 89, false, true, 0.0F, false, false, CreationCategories.WEAPON_HEADS);
            createMetallicEntries(10011, options.MediumanvilId, 46, 523, false, true, 0.0F, false, false, CreationCategories.TOOL_PARTS);
            createMetallicEntries(10015, options.MediumanvilId, 46, 215, false, true, 400.0F, false, false, CreationCategories.TOOLS);
            createMetallicEntries(10015, options.MediumanvilId, 46, 259, false, true, 10.0F, false, false, CreationCategories.COOKING_UTENSILS);
            createMetallicEntries(10015, options.MediumanvilId, 46, 257, false, true, 10.0F, false, false, CreationCategories.COOKING_UTENSILS);
            createMetallicEntries(10015, options.MediumanvilId, 46, 258, false, true, 10.0F, false, false, CreationCategories.COOKING_UTENSILS);
            createMetallicEntries(10015, options.MediumanvilId, 46, 127, false, true, 0.0F, false, false, CreationCategories.TOOL_PARTS);
            createMetallicEntries(10010, options.MediumanvilId, 46, 154, false, true, 0.0F, false, false, CreationCategories.TOOL_PARTS);
            createMetallicEntries(10010, options.MediumanvilId, 46, 389, false, true, 0.0F, false, false, CreationCategories.TOOL_PARTS);
            createMetallicEntries(10010, options.MediumanvilId, 46, 494, false, true, 0.0F, false, false, CreationCategories.TOOL_PARTS);
            createMetallicEntries(10010, options.MediumanvilId, 46, 709, false, true, 0.0F, false, false, CreationCategories.BLADES);
            createMetallicEntries(10010, options.MediumanvilId, 46, 391, false, true, 0.0F, false, false, CreationCategories.TOOL_PARTS);
            createMetallicEntries(10010, options.MediumanvilId, 46, 393, false, true, 0.0F, false, false, CreationCategories.TOOL_PARTS);
            createMetallicEntries(10010, options.MediumanvilId, 46, 395, false, true, 0.0F, false, false, CreationCategories.TOOL_PARTS);
            createMetallicEntries(10010, options.MediumanvilId, 46, 125, false, true, 0.0F, false, false, CreationCategories.TOOL_PARTS);
            createMetallicEntries(10010, options.MediumanvilId, 46, 126, false, true, 0.0F, false, false, CreationCategories.TOOL_PARTS);
            createMetallicEntries(10015, options.MediumanvilId, 46, 734, false, true, 0.0F, false, false, CreationCategories.CONSTRUCTION_MATERIAL);
            createMetallicEntries(10015, options.MediumanvilId, 46, 720, false, true, 0.0F, false, false, CreationCategories.CONSTRUCTION_MATERIAL);
            createMetallicEntries(10015, options.MediumanvilId, 46, 735, false, true, 0.0F, false, false, CreationCategories.CONSTRUCTION_MATERIAL);
            createMetallicEntries(10015, options.MediumanvilId, 46, 131, false, true, 10.0F, false, false, CreationCategories.CONSTRUCTION_MATERIAL);
            createMetallicEntries(10015, options.MediumanvilId, 46, 517, false, true, 10.0F, false, false, CreationCategories.CONSTRUCTION_MATERIAL);
            createMetallicEntries(10015, options.MediumanvilId, 46, 444, false, true, 10.0F, false, false, CreationCategories.CONSTRUCTION_MATERIAL);
            createMetallicEntries(10011, options.MediumanvilId, 46, 451, false, true, 10.0F, false, false, CreationCategories.WEAPON_HEADS);
            createMetallicEntries(10011, options.MediumanvilId, 46, 452, false, true, 10.0F, false, false, CreationCategories.WEAPON_HEADS);
            createMetallicEntries(10011, options.MediumanvilId, 46, 123, false, true, 0.0F, false, false, CreationCategories.TOOL_PARTS);
            createMetallicEntries(10015, options.MediumanvilId, 46, 219, false, true, 0.0F, false, false, CreationCategories.TOOLS);
            createMetallicEntries(10015, options.MediumanvilId, 46, 701, false, true, 0.0F, false, false, CreationCategories.TOOLS);
            createMetallicEntries(10015, options.MediumanvilId, 46, 124, false, true, 0.0F, false, false, CreationCategories.TOOL_PARTS);
            createMetallicEntries(10015, options.MediumanvilId, 46, 24, false, true, 0.0F, false, false, CreationCategories.TOOLS);
            createMetallicEntries(10043, options.MediumanvilId, 46, 228, false, true, 0.0F, false, false, CreationCategories.LIGHTS_AND_LAMPS);
            createMetallicEntries(10043, options.MediumanvilId, 46, 232, false, true, 0.0F, false, false, CreationCategories.CONSTRUCTION_MATERIAL);
            createMetallicEntries(10043, options.MediumanvilId, 46, 229, false, true, 0.0F, false, false, CreationCategories.JEWELRY);
            createMetallicEntries(10034, options.MediumanvilId, 46, 167, false, true, 0.0F, false, false, CreationCategories.LOCKS);
            createMetallicEntries(10034, options.MediumanvilId, 46, 194, false, true, 0.0F, false, false, CreationCategories.LOCKS);
            createMetallicEntries(10034, options.MediumanvilId, 46, 193, false, true, 0.0F, false, false, CreationCategories.LOCKS);
            createMetallicEntries(10034, options.MediumanvilId, 46, 463, false, true, 0.0F, false, false, 0, 25.0, CreationCategories.TOOLS);
            createMetallicEntries(10015, options.MediumanvilId, 46, 185, false, true, 0.0F, false, true, CreationCategories.TOOLS);
            createMetallicEntries(10011, options.MediumanvilId, 698, 935, false, true, 10.0F, false, false, CreationCategories.WEAPON_HEADS);
            createMetallicEntries(10015, options.MediumanvilId, 46, 64, false, true, 0.0F, false, false, CreationCategories.TOOLS);
            // large anvil recipes
            createMetallicEntries(10010, options.MediumanvilId, 46, 148, false, true, 0.0F, false, false, CreationCategories.BLADES);
            createMetallicEntries(10010, options.MediumanvilId, 46, 149, false, true, 0.0F, false, false, CreationCategories.BLADES);
            createMetallicEntries(10010, options.MediumanvilId, 46, 269, false, true, 0.0F, false, false, CreationCategories.TOOL_PARTS);
            createMetallicEntries(10010, options.MediumanvilId, 46, 270, false, true, 0.0F, false, false, CreationCategories.TOOL_PARTS);
            createMetallicEntries(10011, options.MediumanvilId, 46, 91, false, true, 0.0F, false, false, CreationCategories.WEAPON_HEADS);
            createMetallicEntries(10011, options.MediumanvilId, 46, 88, false, true, 0.0F, false, false, CreationCategories.WEAPON_HEADS);
            createMetallicEntries(10011, options.MediumanvilId, 46, 293, false, true, 0.0F, false, false, CreationCategories.WEAPON_HEADS);
            createMetallicEntries(10011, options.MediumanvilId, 46, 295, false, true, 0.0F, false, false, CreationCategories.WEAPON_HEADS);
            createMetallicEntries(10011, options.MediumanvilId, 46, 294, false, true, 0.0F, false, false, CreationCategories.WEAPON_HEADS);
            createMetallicEntries(10011, options.MediumanvilId, 46, 708, false, true, 0.0F, false, false, CreationCategories.WEAPON_HEADS);
            createMetallicEntries(1016, options.MediumanvilId, 205, 710, false, true, 10.0F, false, false, CreationCategories.WEAPONS);
            createMetallicEntries(10015, options.MediumanvilId, 46, 627, false, true, 0.0F, false, false, CreationCategories.ANIMAL_EQUIPMENT_PART);
            createMetallicEntries(10015, options.MediumanvilId, 46, 623, false, true, 0.0F, false, false, CreationCategories.ANIMAL_EQUIPMENT);
            createMetallicEntries(10015, options.MediumanvilId, 46, 75, false, true, 0.0F, false, false, CreationCategories.COOKING_UTENSILS);
            createMetallicEntries(10015, options.MediumanvilId, 46, 351, false, true, 0.0F, false, false, CreationCategories.COOKING_UTENSILS);
            createMetallicEntries(10015, options.MediumanvilId, 46, 721, false, true, 0.0F, false, false, CreationCategories.CONSTRUCTION_MATERIAL);
            createMetallicEntries(10015, options.MediumanvilId, 46, 350, false, true, 0.0F, false, false, CreationCategories.COOKING_UTENSILS);
            createMetallicEntries(10013, options.MediumanvilId, 46, 284, false, true, 10.0F, false, false, CreationCategories.ARMOUR);
            createMetallicEntries(10013, options.MediumanvilId, 46, 280, false, true, 10.0F, false, false, CreationCategories.ARMOUR);
            createMetallicEntries(10013, options.MediumanvilId, 46, 281, false, true, 10.0F, false, false, CreationCategories.ARMOUR);
            createMetallicEntries(10013, options.MediumanvilId, 46, 282, false, true, 10.0F, false, false, CreationCategories.ARMOUR);
            createMetallicEntries(10013, options.MediumanvilId, 46, 283, false, true, 10.0F, false, false, CreationCategories.ARMOUR);
            createMetallicEntries(10013, options.MediumanvilId, 46, 285, false, true, 10.0F, false, false, CreationCategories.ARMOUR);
            createMetallicEntries(10013, options.MediumanvilId, 46, 286, false, true, 10.0F, false, false, CreationCategories.ARMOUR);
            createMetallicEntries(10013, options.MediumanvilId, 46, 287, false, true, 10.0F, false, false, CreationCategories.ARMOUR);
            createMetallicEntries(10012, options.MediumanvilId, 46, 288, false, true, 10.0F, false, false, CreationCategories.RESOURCES);
            createMetallicEntries(10043, options.MediumanvilId, 46, 326, false, true, 10.0F, false, false, CreationCategories.DECORATION);
            createMetallicEntries(10015, options.MediumanvilId, 46, 135, false, true, 0.0F, false, false, CreationCategories.LIGHTS_AND_LAMPS);
            createMetallicEntries(10015, options.MediumanvilId, 46, 497, false, true, 0.0F, false, false, CreationCategories.LIGHTS_AND_LAMPS);
            createMetallicEntries(10015, options.MediumanvilId, 46, 675, false, true, 0.0F, false, false, CreationCategories.LIGHTS_AND_LAMPS);
            createMetallicEntries(10015, options.MediumanvilId, 46, 660, false, true, 0.0F, false, false, CreationCategories.LIGHTS_AND_LAMPS);
            createMetallicEntries(10015, options.MediumanvilId, 46, 674, false, true, 0.0F, false, false, CreationCategories.LIGHTS_AND_LAMPS);
            createMetallicEntries(10014, options.MediumanvilId, 46, 86, false, true, 0.0F, false, false, CreationCategories.SHIELDS);
            createMetallicEntries(10014, options.MediumanvilId, 46, 4, false, true, 0.0F, false, false, CreationCategories.SHIELDS);
            createMetallicEntries(10014, options.MediumanvilId, 46, 83, false, true, 0.0F, false, false, CreationCategories.SHIELDS);
            createMetallicEntries(10015, options.MediumanvilId, 46, 121, false, true, 0.0F, false, false, CreationCategories.TOOL_PARTS);
            createMetallicEntries(10034, options.MediumanvilId, 46, 252, false, true, 0.0F, false, false, CreationCategories.LOCKS);
            createMetallicEntries(10034, options.MediumanvilId, 46, 568, false, true, 0.0F, false, false, CreationCategories.LOCKS);
            createMetallicEntries(10015, options.MediumanvilId, 46, 547, false, true, 0.0F, false, true, CreationCategories.SHIPBUILDING);
            createMetallicEntries(10015, options.MediumanvilId, 205, 1115, false, true, 0.0F, false, false, CreationCategories.TOOLS);
        }
        else {
            // small anvil recipes
            createSimpleEntry(10015, 63, 46, options.MediumanvilId, false, true, 0.0F, false, false, CreationCategories.TOOLS);
            createSimpleEntry(10015, 62, 46, options.MediumanvilId, false, true, 0.0F, false, false, CreationCategories.TOOLS);
            createSimpleEntry(10010, options.MediumanvilId, 46, 147, false, true, 0.0F, false, false, CreationCategories.BLADES);
            createSimpleEntry(10010, options.MediumanvilId, 694, 147, false, true, 0.0F, false, false, CreationCategories.BLADES);
            createSimpleEntry(10010, options.MediumanvilId, 837, 147, false, true, 0.0F, false, false, CreationCategories.BLADES);
            createSimpleEntry(10010, options.MediumanvilId, 698, 147, false, true, 0.0F, false, false, CreationCategories.BLADES);
            createSimpleEntry(10010, options.MediumanvilId, 205, 147, false, true, 0.0F, false, false, CreationCategories.BLADES);
            createSimpleEntry(10011, options.MediumanvilId, 46, 89, false, true, 0.0F, false, false, CreationCategories.WEAPON_HEADS);
            createSimpleEntry(10011, options.MediumanvilId, 46, 523, false, true, 0.0F, false, false, CreationCategories.TOOL_PARTS);
            createSimpleEntry(10011, options.MediumanvilId, 694, 89, false, true, 0.0F, false, false, CreationCategories.WEAPON_HEADS);
            createSimpleEntry(10011, options.MediumanvilId, 694, 523, false, true, 0.0F, false, false, CreationCategories.TOOL_PARTS);
            createSimpleEntry(10011, options.MediumanvilId, 837, 89, false, true, 0.0F, false, false, CreationCategories.WEAPON_HEADS);
            createSimpleEntry(10011, options.MediumanvilId, 837, 523, false, true, 0.0F, false, false, CreationCategories.TOOL_PARTS);
            createSimpleEntry(10011, options.MediumanvilId, 205, 89, false, true, 0.0F, false, false, CreationCategories.WEAPON_HEADS);
            createSimpleEntry(10011, options.MediumanvilId, 205, 523, false, true, 0.0F, false, false, CreationCategories.TOOL_PARTS);
            createSimpleEntry(10011, options.MediumanvilId, 698, 89, false, true, 0.0F, false, false, CreationCategories.WEAPON_HEADS);
            createSimpleEntry(10011, options.MediumanvilId, 698, 523, false, true, 0.0F, false, false, CreationCategories.TOOL_PARTS);
            createSimpleEntry(10015, options.MediumanvilId, 46, 215, false, true, 400.0F, false, false, CreationCategories.TOOLS);
            createSimpleEntry(10015, options.MediumanvilId, 46, 259, false, true, 10.0F, false, false, CreationCategories.COOKING_UTENSILS);
            createSimpleEntry(10015, options.MediumanvilId, 46, 257, false, true, 10.0F, false, false, CreationCategories.COOKING_UTENSILS);
            createSimpleEntry(10015, options.MediumanvilId, 46, 258, false, true, 10.0F, false, false, CreationCategories.COOKING_UTENSILS);
            createSimpleEntry(10015, options.MediumanvilId, 45, 259, false, true, 10.0F, false, false, CreationCategories.COOKING_UTENSILS);
            createSimpleEntry(10015, options.MediumanvilId, 45, 257, false, true, 10.0F, false, false, CreationCategories.COOKING_UTENSILS);
            createSimpleEntry(10015, options.MediumanvilId, 45, 258, false, true, 10.0F, false, false, CreationCategories.COOKING_UTENSILS);
            createSimpleEntry(10015, options.MediumanvilId, 47, 216, false, true, 400.0F, false, false, CreationCategories.TOOLS);
            createSimpleEntry(10015, options.MediumanvilId, 46, 127, false, true, 0.0F, false, false, CreationCategories.TOOL_PARTS);
            createSimpleEntry(10010, options.MediumanvilId, 46, 154, false, true, 0.0F, false, false, CreationCategories.TOOL_PARTS);
            createSimpleEntry(10010, options.MediumanvilId, 46, 389, false, true, 0.0F, false, false, CreationCategories.TOOL_PARTS);
            createSimpleEntry(10010, options.MediumanvilId, 46, 494, false, true, 0.0F, false, false, CreationCategories.TOOL_PARTS);
            createSimpleEntry(10010, options.MediumanvilId, 46, 709, false, true, 0.0F, false, false, CreationCategories.BLADES);
            createSimpleEntry(10010, options.MediumanvilId, 205, 709, false, true, 0.0F, false, false, CreationCategories.BLADES);
            createSimpleEntry(10010, options.MediumanvilId, 698, 709, false, true, 0.0F, false, false, CreationCategories.BLADES);
            createSimpleEntry(10010, options.MediumanvilId, 694, 709, false, true, 0.0F, false, false, CreationCategories.BLADES);
            createSimpleEntry(10010, options.MediumanvilId, 837, 709, false, true, 0.0F, false, false, CreationCategories.BLADES);
            createSimpleEntry(10010, options.MediumanvilId, 46, 391, false, true, 0.0F, false, false, CreationCategories.TOOL_PARTS);
            createSimpleEntry(10010, options.MediumanvilId, 46, 393, false, true, 0.0F, false, false, CreationCategories.TOOL_PARTS);
            createSimpleEntry(10010, options.MediumanvilId, 205, 393, false, true, 0.0F, false, false, CreationCategories.TOOL_PARTS);
            createSimpleEntry(10010, options.MediumanvilId, 694, 393, false, true, 0.0F, false, false, CreationCategories.TOOL_PARTS);
            createSimpleEntry(10010, options.MediumanvilId, 837, 393, false, true, 0.0F, false, false, CreationCategories.TOOL_PARTS);
            createSimpleEntry(10010, options.MediumanvilId, 698, 393, false, true, 0.0F, false, false, CreationCategories.TOOL_PARTS);
            createSimpleEntry(10010, options.MediumanvilId, 46, 395, false, true, 0.0F, false, false, CreationCategories.TOOL_PARTS);
            createSimpleEntry(10015, options.MediumanvilId, 46, 734, false, true, 0.0F, false, false, CreationCategories.CONSTRUCTION_MATERIAL);
            createSimpleEntry(10015, options.MediumanvilId, 221, 720, false, true, 0.0F, false, false, CreationCategories.CONSTRUCTION_MATERIAL);
            createSimpleEntry(10015, options.MediumanvilId, 46, 735, false, true, 0.0F, false, false, CreationCategories.CONSTRUCTION_MATERIAL);
            createSimpleEntry(10010, options.MediumanvilId, 46, 125, false, true, 0.0F, false, false, CreationCategories.TOOL_PARTS);
            createSimpleEntry(10010, options.MediumanvilId, 46, 126, false, true, 0.0F, false, false, CreationCategories.TOOL_PARTS);
            createSimpleEntry(10010, options.MediumanvilId, 205, 126, false, true, 0.0F, false, false, CreationCategories.TOOL_PARTS);
            createSimpleEntry(10010, options.MediumanvilId, 698, 126, false, true, 0.0F, false, false, CreationCategories.TOOL_PARTS);
            createSimpleEntry(10010, options.MediumanvilId, 694, 126, false, true, 0.0F, false, false, CreationCategories.TOOL_PARTS);
            createSimpleEntry(10010, options.MediumanvilId, 837, 126, false, true, 0.0F, false, false, CreationCategories.TOOL_PARTS);
            createSimpleEntry(10015, options.MediumanvilId, 46, 131, false, true, 10.0F, false, false, CreationCategories.CONSTRUCTION_MATERIAL);
            createSimpleEntry(10015, options.MediumanvilId, 205, 131, false, true, 10.0F, false, false, CreationCategories.CONSTRUCTION_MATERIAL);
            createSimpleEntry(10015, options.MediumanvilId, 47, 131, false, true, 10.0F, false, false, CreationCategories.CONSTRUCTION_MATERIAL);
            createSimpleEntry(10015, options.MediumanvilId, 45, 131, false, true, 10.0F, false, false, CreationCategories.CONSTRUCTION_MATERIAL);
            createSimpleEntry(10015, options.MediumanvilId, 44, 131, false, true, 10.0F, false, false, CreationCategories.CONSTRUCTION_MATERIAL);
            createSimpleEntry(10015, options.MediumanvilId, 223, 131, false, true, 10.0F, false, false, CreationCategories.CONSTRUCTION_MATERIAL);
            createSimpleEntry(10015, options.MediumanvilId, 694, 131, false, true, 10.0F, false, false, CreationCategories.CONSTRUCTION_MATERIAL);
            createSimpleEntry(10015, options.MediumanvilId, 837, 131, false, true, 10.0F, false, false, CreationCategories.CONSTRUCTION_MATERIAL);
            createSimpleEntry(10015, options.MediumanvilId, 698, 131, false, true, 10.0F, false, false, CreationCategories.CONSTRUCTION_MATERIAL);
            createSimpleEntry(10015, options.MediumanvilId, 46, 517, false, true, 10.0F, false, false, CreationCategories.CONSTRUCTION_MATERIAL);
            createSimpleEntry(10015, options.MediumanvilId, 205, 517, false, true, 10.0F, false, false, CreationCategories.CONSTRUCTION_MATERIAL);
            createSimpleEntry(10015, options.MediumanvilId, 47, 517, false, true, 10.0F, false, false, CreationCategories.CONSTRUCTION_MATERIAL);
            createSimpleEntry(10015, options.MediumanvilId, 45, 517, false, true, 10.0F, false, false, CreationCategories.CONSTRUCTION_MATERIAL);
            createSimpleEntry(10015, options.MediumanvilId, 44, 517, false, true, 10.0F, false, false, CreationCategories.CONSTRUCTION_MATERIAL);
            createSimpleEntry(10015, options.MediumanvilId, 223, 517, false, true, 10.0F, false, false, CreationCategories.CONSTRUCTION_MATERIAL);
            createSimpleEntry(10015, options.MediumanvilId, 46, 444, false, true, 10.0F, false, false, CreationCategories.CONSTRUCTION_MATERIAL);
            createSimpleEntry(10015, options.MediumanvilId, 205, 444, false, true, 10.0F, false, false, CreationCategories.CONSTRUCTION_MATERIAL);
            createSimpleEntry(10015, options.MediumanvilId, 47, 444, false, true, 10.0F, false, false, CreationCategories.CONSTRUCTION_MATERIAL);
            createSimpleEntry(10015, options.MediumanvilId, 45, 444, false, true, 10.0F, false, false, CreationCategories.CONSTRUCTION_MATERIAL);
            createSimpleEntry(10015, options.MediumanvilId, 44, 444, false, true, 10.0F, false, false, CreationCategories.CONSTRUCTION_MATERIAL);
            createSimpleEntry(10015, options.MediumanvilId, 223, 444, false, true, 10.0F, false, false, CreationCategories.CONSTRUCTION_MATERIAL);
            createSimpleEntry(10011, options.MediumanvilId, 46, 451, false, true, 10.0F, false, false, CreationCategories.WEAPON_HEADS);
            createSimpleEntry(10011, options.MediumanvilId, 698, 451, false, true, 10.0F, false, false, CreationCategories.WEAPON_HEADS);
            createSimpleEntry(10011, options.MediumanvilId, 694, 451, false, true, 10.0F, false, false, CreationCategories.WEAPON_HEADS);
            createSimpleEntry(10011, options.MediumanvilId, 837, 451, false, true, 10.0F, false, false, CreationCategories.WEAPON_HEADS);
            createSimpleEntry(10011, options.MediumanvilId, 205, 451, false, true, 10.0F, false, false, CreationCategories.WEAPON_HEADS);
            createSimpleEntry(10011, options.MediumanvilId, 47, 451, false, true, 10.0F, false, false, CreationCategories.WEAPON_HEADS);
            createSimpleEntry(10011, options.MediumanvilId, 45, 451, false, true, 10.0F, false, false, CreationCategories.WEAPON_HEADS);
            createSimpleEntry(10011, options.MediumanvilId, 44, 451, false, true, 10.0F, false, false, CreationCategories.WEAPON_HEADS);
            createSimpleEntry(10011, options.MediumanvilId, 223, 451, false, true, 10.0F, false, false, CreationCategories.WEAPON_HEADS);
            createSimpleEntry(10011, options.MediumanvilId, 46, 452, false, true, 10.0F, false, false, CreationCategories.WEAPON_HEADS);
            createSimpleEntry(10011, options.MediumanvilId, 698, 452, false, true, 10.0F, false, false, CreationCategories.WEAPON_HEADS);
            createSimpleEntry(10011, options.MediumanvilId, 694, 452, false, true, 10.0F, false, false, CreationCategories.WEAPON_HEADS);
            createSimpleEntry(10011, options.MediumanvilId, 837, 452, false, true, 10.0F, false, false, CreationCategories.WEAPON_HEADS);
            createSimpleEntry(10011, options.MediumanvilId, 205, 452, false, true, 10.0F, false, false, CreationCategories.WEAPON_HEADS);
            createSimpleEntry(10011, options.MediumanvilId, 47, 452, false, true, 10.0F, false, false, CreationCategories.WEAPON_HEADS);
            createSimpleEntry(10011, options.MediumanvilId, 45, 452, false, true, 10.0F, false, false, CreationCategories.WEAPON_HEADS);
            createSimpleEntry(10011, options.MediumanvilId, 44, 452, false, true, 10.0F, false, false, CreationCategories.WEAPON_HEADS);
            createSimpleEntry(10011, options.MediumanvilId, 223, 452, false, true, 10.0F, false, false, CreationCategories.WEAPON_HEADS);
            createSimpleEntry(10011, options.MediumanvilId, 46, 123, false, true, 0.0F, false, false, CreationCategories.TOOL_PARTS);
            createSimpleEntry(10011, options.MediumanvilId, 205, 123, false, true, 0.0F, false, false, CreationCategories.TOOL_PARTS);
            createSimpleEntry(10011, options.MediumanvilId, 694, 123, false, true, 0.0F, false, false, CreationCategories.TOOL_PARTS);
            createSimpleEntry(10011, options.MediumanvilId, 837, 123, false, true, 0.0F, false, false, CreationCategories.TOOL_PARTS);
            createSimpleEntry(10011, options.MediumanvilId, 698, 123, false, true, 0.0F, false, false, CreationCategories.TOOL_PARTS);
            createSimpleEntry(10015, options.MediumanvilId, 46, 219, false, true, 0.0F, false, false, CreationCategories.TOOLS);
            createSimpleEntry(10015, options.MediumanvilId, 46, 701, false, true, 0.0F, false, false, CreationCategories.TOOLS);
            createSimpleEntry(10015, options.MediumanvilId, 46, 124, false, true, 0.0F, false, false, CreationCategories.TOOL_PARTS);
            createSimpleEntry(10015, options.MediumanvilId, 46, 24, false, true, 0.0F, false, false, CreationCategories.TOOLS);
            createSimpleEntry(10043, options.MediumanvilId, 44, 229, false, true, 0.0F, false, false, CreationCategories.JEWELRY);
            createSimpleEntry(10043, options.MediumanvilId, 45, 229, false, true, 0.0F, false, false, CreationCategories.JEWELRY);
            createSimpleEntry(10043, options.MediumanvilId, 44, 228, false, true, 0.0F, false, false, CreationCategories.LIGHTS_AND_LAMPS);
            createSimpleEntry(10043, options.MediumanvilId, 45, 228, false, true, 0.0F, false, false, CreationCategories.LIGHTS_AND_LAMPS);
            createSimpleEntry(10043, options.MediumanvilId, 46, 228, false, true, 0.0F, false, false, CreationCategories.LIGHTS_AND_LAMPS);
            createSimpleEntry(10043, options.MediumanvilId, 698, 228, false, true, 0.0F, false, false, CreationCategories.LIGHTS_AND_LAMPS);
            createSimpleEntry(10043, options.MediumanvilId, 694, 228, false, true, 0.0F, false, false, CreationCategories.LIGHTS_AND_LAMPS);
            createSimpleEntry(10043, options.MediumanvilId, 837, 228, false, true, 0.0F, false, false, CreationCategories.LIGHTS_AND_LAMPS);
            createSimpleEntry(10043, options.MediumanvilId, 47, 228, false, true, 0.0F, false, false, CreationCategories.LIGHTS_AND_LAMPS);
            createSimpleEntry(10043, options.MediumanvilId, 44, 232, false, true, 0.0F, false, false, CreationCategories.CONSTRUCTION_MATERIAL);
            createSimpleEntry(10043, options.MediumanvilId, 45, 232, false, true, 0.0F, false, false, CreationCategories.CONSTRUCTION_MATERIAL);
            createSimpleEntry(10043, options.MediumanvilId, 46, 232, false, true, 0.0F, false, false, CreationCategories.CONSTRUCTION_MATERIAL);
            createSimpleEntry(10043, options.MediumanvilId, 47, 232, false, true, 0.0F, false, false, CreationCategories.CONSTRUCTION_MATERIAL);
            createSimpleEntry(10043, options.MediumanvilId, 223, 232, false, true, 0.0F, false, false, CreationCategories.CONSTRUCTION_MATERIAL);
            createSimpleEntry(10043, options.MediumanvilId, 221, 232, false, true, 0.0F, false, false, CreationCategories.CONSTRUCTION_MATERIAL);
            createSimpleEntry(10043, options.MediumanvilId, 49, 232, false, true, 0.0F, false, false, CreationCategories.CONSTRUCTION_MATERIAL);
            createSimpleEntry(10043, options.MediumanvilId, 205, 232, false, true, 0.0F, false, false, CreationCategories.CONSTRUCTION_MATERIAL);
            createSimpleEntry(10043, options.MediumanvilId, 694, 232, false, true, 0.0F, false, false, CreationCategories.CONSTRUCTION_MATERIAL);
            createSimpleEntry(10043, options.MediumanvilId, 837, 232, false, true, 0.0F, false, false, CreationCategories.CONSTRUCTION_MATERIAL);
            createSimpleEntry(10043, options.MediumanvilId, 698, 232, false, true, 0.0F, false, false, CreationCategories.CONSTRUCTION_MATERIAL);
            createSimpleEntry(10034, options.MediumanvilId, 46, 167, false, true, 0.0F, false, false, CreationCategories.LOCKS);
            createSimpleEntry(10034, options.MediumanvilId, 46, 194, false, true, 0.0F, false, false, CreationCategories.LOCKS);
            createSimpleEntry(10034, options.MediumanvilId, 46, 193, false, true, 0.0F, false, false, CreationCategories.LOCKS);
            createSimpleEntry(10034, options.MediumanvilId, 694, 167, false, true, 0.0F, false, false, CreationCategories.LOCKS);
            createSimpleEntry(10034, options.MediumanvilId, 694, 194, false, true, 0.0F, false, false, CreationCategories.LOCKS);
            createSimpleEntry(10034, options.MediumanvilId, 694, 193, false, true, 0.0F, false, false, CreationCategories.LOCKS);
            createSimpleEntry(10034, options.MediumanvilId, 837, 167, false, true, 0.0F, false, false, CreationCategories.LOCKS);
            createSimpleEntry(10034, options.MediumanvilId, 837, 194, false, true, 0.0F, false, false, CreationCategories.LOCKS);
            createSimpleEntry(10034, options.MediumanvilId, 837, 193, false, true, 0.0F, false, false, CreationCategories.LOCKS);
            createSimpleEntry(10034, options.MediumanvilId, 698, 167, false, true, 0.0F, false, false, CreationCategories.LOCKS);
            createSimpleEntry(10034, options.MediumanvilId, 698, 194, false, true, 0.0F, false, false, CreationCategories.LOCKS);
            createSimpleEntry(10034, options.MediumanvilId, 698, 193, false, true, 0.0F, false, false, CreationCategories.LOCKS);
            createSimpleEntry(10034, options.MediumanvilId, 46, 463, false, true, 0.0F, false, false, 0, 25.0, CreationCategories.TOOLS);
            createSimpleEntry(10034, options.MediumanvilId, 205, 463, false, true, 0.0F, false, false, 0, 25.0, CreationCategories.TOOLS);
            createSimpleEntry(10034, options.MediumanvilId, 694, 463, false, true, 0.0F, false, false, 0, 25.0, CreationCategories.TOOLS);
            createSimpleEntry(10034, options.MediumanvilId, 837, 463, false, true, 0.0F, false, false, 0, 25.0, CreationCategories.TOOLS);
            createSimpleEntry(10034, options.MediumanvilId, 698, 463, false, true, 0.0F, false, false, 0, 25.0, CreationCategories.TOOLS);
            createSimpleEntry(10034, options.MediumanvilId, 47, 463, false, true, 0.0F, false, false, 0, 25.0, CreationCategories.TOOLS);
            createSimpleEntry(10015, options.MediumanvilId, 46, 185, false, true, 0.0F, false, true, CreationCategories.TOOLS);
            createSimpleEntry(10011, options.MediumanvilId, 698, 935, false, true, 10.0F, false, false, CreationCategories.WEAPON_HEADS);
            createSimpleEntry(10011, options.MediumanvilId, 694, 935, false, true, 10.0F, false, false, CreationCategories.WEAPON_HEADS);
            createSimpleEntry(10011, options.MediumanvilId, 837, 935, false, true, 10.0F, false, false, CreationCategories.WEAPON_HEADS);
            createSimpleEntry(10011, options.MediumanvilId, 205, 935, false, true, 10.0F, false, false, CreationCategories.WEAPON_HEADS);
            createSimpleEntry(10011, options.MediumanvilId, 47, 935, false, true, 10.0F, false, false, CreationCategories.WEAPON_HEADS);
            createSimpleEntry(10011, options.MediumanvilId, 45, 935, false, true, 10.0F, false, false, CreationCategories.WEAPON_HEADS);
            createSimpleEntry(10011, options.MediumanvilId, 44, 935, false, true, 10.0F, false, false, CreationCategories.WEAPON_HEADS);
            createSimpleEntry(10011, options.MediumanvilId, 223, 935, false, true, 10.0F, false, false, CreationCategories.WEAPON_HEADS);
            createSimpleEntry(10015, options.MediumanvilId, 46, 64, false, true, 0.0F, false, false, CreationCategories.TOOLS);

            // large anvil recipes
            createSimpleEntry(10010, options.MediumanvilId, 46, 148, false, true, 0.0F, false, false, CreationCategories.BLADES);
            createSimpleEntry(10010, options.MediumanvilId, 694, 148, false, true, 0.0F, false, false, CreationCategories.BLADES);
            createSimpleEntry(10010, options.MediumanvilId, 837, 148, false, true, 0.0F, false, false, CreationCategories.BLADES);
            createSimpleEntry(10010, options.MediumanvilId, 698, 148, false, true, 0.0F, false, false, CreationCategories.BLADES);
            createSimpleEntry(10010, options.MediumanvilId, 205, 148, false, true, 0.0F, false, false, CreationCategories.BLADES);
            createSimpleEntry(10010, options.MediumanvilId, 694, 149, false, true, 0.0F, false, false, CreationCategories.BLADES);
            createSimpleEntry(10010, options.MediumanvilId, 837, 149, false, true, 0.0F, false, false, CreationCategories.BLADES);
            createSimpleEntry(10010, options.MediumanvilId, 698, 149, false, true, 0.0F, false, false, CreationCategories.BLADES);
            createSimpleEntry(10010, options.MediumanvilId, 46, 149, false, true, 0.0F, false, false, CreationCategories.BLADES);
            createSimpleEntry(10010, options.MediumanvilId, 205, 149, false, true, 0.0F, false, false, CreationCategories.BLADES);
            createSimpleEntry(10010, options.MediumanvilId, 46, 269, false, true, 0.0F, false, false, CreationCategories.TOOL_PARTS);
            createSimpleEntry(10010, options.MediumanvilId, 46, 270, false, true, 0.0F, false, false, CreationCategories.TOOL_PARTS);
            createSimpleEntry(10010, options.MediumanvilId, 698, 270, false, true, 0.0F, false, false, CreationCategories.TOOL_PARTS);
            createSimpleEntry(10010, options.MediumanvilId, 205, 270, false, true, 0.0F, false, false, CreationCategories.TOOL_PARTS);
            createSimpleEntry(10010, options.MediumanvilId, 694, 270, false, true, 0.0F, false, false, CreationCategories.TOOL_PARTS);
            createSimpleEntry(10010, options.MediumanvilId, 837, 270, false, true, 0.0F, false, false, CreationCategories.TOOL_PARTS);
            createSimpleEntry(10011, options.MediumanvilId, 46, 91, false, true, 0.0F, false, false, CreationCategories.WEAPON_HEADS);
            createSimpleEntry(10011, options.MediumanvilId, 46, 88, false, true, 0.0F, false, false, CreationCategories.WEAPON_HEADS);
            createSimpleEntry(10011, options.MediumanvilId, 46, 293, false, true, 0.0F, false, false, CreationCategories.WEAPON_HEADS);
            createSimpleEntry(10011, options.MediumanvilId, 46, 295, false, true, 0.0F, false, false, CreationCategories.WEAPON_HEADS);
            createSimpleEntry(10011, options.MediumanvilId, 46, 294, false, true, 0.0F, false, false, CreationCategories.WEAPON_HEADS);
            createSimpleEntry(10011, options.MediumanvilId, 46, 708, false, true, 0.0F, false, false, CreationCategories.WEAPON_HEADS);
            createSimpleEntry(10011, options.MediumanvilId, 694, 91, false, true, 0.0F, false, false, CreationCategories.WEAPON_HEADS);
            createSimpleEntry(10011, options.MediumanvilId, 694, 88, false, true, 0.0F, false, false, CreationCategories.WEAPON_HEADS);
            createSimpleEntry(10011, options.MediumanvilId, 694, 293, false, true, 0.0F, false, false, CreationCategories.WEAPON_HEADS);
            createSimpleEntry(10011, options.MediumanvilId, 694, 295, false, true, 0.0F, false, false, CreationCategories.WEAPON_HEADS);
            createSimpleEntry(10011, options.MediumanvilId, 694, 294, false, true, 0.0F, false, false, CreationCategories.WEAPON_HEADS);
            createSimpleEntry(10011, options.MediumanvilId, 694, 708, false, true, 0.0F, false, false, CreationCategories.WEAPON_HEADS);
            createSimpleEntry(10011, options.MediumanvilId, 837, 91, false, true, 0.0F, false, false, CreationCategories.WEAPON_HEADS);
            createSimpleEntry(10011, options.MediumanvilId, 837, 88, false, true, 0.0F, false, false, CreationCategories.WEAPON_HEADS);
            createSimpleEntry(10011, options.MediumanvilId, 837, 293, false, true, 0.0F, false, false, CreationCategories.WEAPON_HEADS);
            createSimpleEntry(10011, options.MediumanvilId, 837, 295, false, true, 0.0F, false, false, CreationCategories.WEAPON_HEADS);
            createSimpleEntry(10011, options.MediumanvilId, 837, 294, false, true, 0.0F, false, false, CreationCategories.WEAPON_HEADS);
            createSimpleEntry(10011, options.MediumanvilId, 837, 708, false, true, 0.0F, false, false, CreationCategories.WEAPON_HEADS);
            createSimpleEntry(10011, options.MediumanvilId, 205, 91, false, true, 0.0F, false, false, CreationCategories.WEAPON_HEADS);
            createSimpleEntry(10011, options.MediumanvilId, 205, 88, false, true, 0.0F, false, false, CreationCategories.WEAPON_HEADS);
            createSimpleEntry(10011, options.MediumanvilId, 205, 293, false, true, 0.0F, false, false, CreationCategories.WEAPON_HEADS);
            createSimpleEntry(10011, options.MediumanvilId, 205, 295, false, true, 0.0F, false, false, CreationCategories.WEAPON_HEADS);
            createSimpleEntry(10011, options.MediumanvilId, 205, 294, false, true, 0.0F, false, false, CreationCategories.WEAPON_HEADS);
            createSimpleEntry(10011, options.MediumanvilId, 205, 708, false, true, 0.0F, false, false, CreationCategories.WEAPON_HEADS);
            createSimpleEntry(10011, options.MediumanvilId, 698, 91, false, true, 0.0F, false, false, CreationCategories.WEAPON_HEADS);
            createSimpleEntry(10011, options.MediumanvilId, 698, 88, false, true, 0.0F, false, false, CreationCategories.WEAPON_HEADS);
            createSimpleEntry(10011, options.MediumanvilId, 698, 293, false, true, 0.0F, false, false, CreationCategories.WEAPON_HEADS);
            createSimpleEntry(10011, options.MediumanvilId, 698, 295, false, true, 0.0F, false, false, CreationCategories.WEAPON_HEADS);
            createSimpleEntry(10011, options.MediumanvilId, 698, 294, false, true, 0.0F, false, false, CreationCategories.WEAPON_HEADS);
            createSimpleEntry(10011, options.MediumanvilId, 698, 708, false, true, 0.0F, false, false, CreationCategories.WEAPON_HEADS);
            createSimpleEntry(1016, options.MediumanvilId, 205, 710, false, true, 10.0F, false, false, CreationCategories.WEAPONS);
            createSimpleEntry(10015, options.MediumanvilId, 46, 627, false, true, 0.0F, false, false, CreationCategories.ANIMAL_EQUIPMENT_PART);
            createSimpleEntry(10015, options.MediumanvilId, 46, 623, false, true, 0.0F, false, false, CreationCategories.ANIMAL_EQUIPMENT);
            createSimpleEntry(10015, options.MediumanvilId, 205, 627, false, true, 0.0F, false, false, CreationCategories.ANIMAL_EQUIPMENT_PART);
            createSimpleEntry(10015, options.MediumanvilId, 205, 623, false, true, 0.0F, false, false, CreationCategories.ANIMAL_EQUIPMENT);
            createSimpleEntry(10043, options.MediumanvilId, 44, 623, false, true, 0.0F, false, false, CreationCategories.ANIMAL_EQUIPMENT);
            createSimpleEntry(10043, options.MediumanvilId, 45, 623, false, true, 0.0F, false, false, CreationCategories.ANIMAL_EQUIPMENT);
            createSimpleEntry(10015, options.MediumanvilId, 46, 75, false, true, 0.0F, false, false, CreationCategories.COOKING_UTENSILS);
            createSimpleEntry(10015, options.MediumanvilId, 46, 351, false, true, 0.0F, false, false, CreationCategories.COOKING_UTENSILS);
            createSimpleEntry(10015, options.MediumanvilId, 223, 721, false, true, 0.0F, false, false, CreationCategories.CONSTRUCTION_MATERIAL);
            createSimpleEntry(10015, options.MediumanvilId, 46, 350, false, true, 0.0F, false, false, CreationCategories.COOKING_UTENSILS);
            createSimpleEntry(10013, options.MediumanvilId, 205, 284, false, true, 10.0F, false, false, CreationCategories.ARMOUR);
            createSimpleEntry(10013, options.MediumanvilId, 205, 280, false, true, 10.0F, false, false, CreationCategories.ARMOUR);
            createSimpleEntry(10013, options.MediumanvilId, 205, 281, false, true, 10.0F, false, false, CreationCategories.ARMOUR);
            createSimpleEntry(10013, options.MediumanvilId, 205, 282, false, true, 10.0F, false, false, CreationCategories.ARMOUR);
            createSimpleEntry(10013, options.MediumanvilId, 205, 283, false, true, 10.0F, false, false, CreationCategories.ARMOUR);
            createSimpleEntry(10013, options.MediumanvilId, 205, 285, false, true, 10.0F, false, false, CreationCategories.ARMOUR);
            createSimpleEntry(10013, options.MediumanvilId, 205, 286, false, true, 10.0F, false, false, CreationCategories.ARMOUR);
            createSimpleEntry(10013, options.MediumanvilId, 205, 287, false, true, 10.0F, false, false, CreationCategories.ARMOUR);
            createSimpleEntry(10013, options.MediumanvilId, 698, 284, false, true, 10.0F, false, false, CreationCategories.ARMOUR);
            createSimpleEntry(10013, options.MediumanvilId, 698, 280, false, true, 10.0F, false, false, CreationCategories.ARMOUR);
            createSimpleEntry(10013, options.MediumanvilId, 698, 281, false, true, 10.0F, false, false, CreationCategories.ARMOUR);
            createSimpleEntry(10013, options.MediumanvilId, 698, 282, false, true, 10.0F, false, false, CreationCategories.ARMOUR);
            createSimpleEntry(10013, options.MediumanvilId, 698, 283, false, true, 10.0F, false, false, CreationCategories.ARMOUR);
            createSimpleEntry(10013, options.MediumanvilId, 698, 285, false, true, 10.0F, false, false, CreationCategories.ARMOUR);
            createSimpleEntry(10013, options.MediumanvilId, 698, 286, false, true, 10.0F, false, false, CreationCategories.ARMOUR);
            createSimpleEntry(10013, options.MediumanvilId, 698, 287, false, true, 10.0F, false, false, CreationCategories.ARMOUR);
            createSimpleEntry(10013, options.MediumanvilId, 694, 284, false, true, 10.0F, false, false, CreationCategories.ARMOUR);
            createSimpleEntry(10013, options.MediumanvilId, 694, 280, false, true, 10.0F, false, false, CreationCategories.ARMOUR);
            createSimpleEntry(10013, options.MediumanvilId, 694, 281, false, true, 10.0F, false, false, CreationCategories.ARMOUR);
            createSimpleEntry(10013, options.MediumanvilId, 694, 282, false, true, 10.0F, false, false, CreationCategories.ARMOUR);
            createSimpleEntry(10013, options.MediumanvilId, 694, 283, false, true, 10.0F, false, false, CreationCategories.ARMOUR);
            createSimpleEntry(10013, options.MediumanvilId, 694, 285, false, true, 10.0F, false, false, CreationCategories.ARMOUR);
            createSimpleEntry(10013, options.MediumanvilId, 694, 286, false, true, 10.0F, false, false, CreationCategories.ARMOUR);
            createSimpleEntry(10013, options.MediumanvilId, 694, 287, false, true, 10.0F, false, false, CreationCategories.ARMOUR);
            createSimpleEntry(10013, options.MediumanvilId, 837, 284, false, true, 10.0F, false, false, CreationCategories.ARMOUR);
            createSimpleEntry(10013, options.MediumanvilId, 837, 280, false, true, 10.0F, false, false, CreationCategories.ARMOUR);
            createSimpleEntry(10013, options.MediumanvilId, 837, 281, false, true, 10.0F, false, false, CreationCategories.ARMOUR);
            createSimpleEntry(10013, options.MediumanvilId, 837, 282, false, true, 10.0F, false, false, CreationCategories.ARMOUR);
            createSimpleEntry(10013, options.MediumanvilId, 837, 283, false, true, 10.0F, false, false, CreationCategories.ARMOUR);
            createSimpleEntry(10013, options.MediumanvilId, 837, 285, false, true, 10.0F, false, false, CreationCategories.ARMOUR);
            createSimpleEntry(10013, options.MediumanvilId, 837, 286, false, true, 10.0F, false, false, CreationCategories.ARMOUR);
            createSimpleEntry(10013, options.MediumanvilId, 837, 287, false, true, 10.0F, false, false, CreationCategories.ARMOUR);
            createSimpleEntry(10013, options.MediumanvilId, 46, 284, false, true, 10.0F, false, false, CreationCategories.ARMOUR);
            createSimpleEntry(10013, options.MediumanvilId, 46, 280, false, true, 10.0F, false, false, CreationCategories.ARMOUR);
            createSimpleEntry(10013, options.MediumanvilId, 46, 281, false, true, 10.0F, false, false, CreationCategories.ARMOUR);
            createSimpleEntry(10013, options.MediumanvilId, 46, 282, false, true, 10.0F, false, false, CreationCategories.ARMOUR);
            createSimpleEntry(10013, options.MediumanvilId, 46, 283, false, true, 10.0F, false, false, CreationCategories.ARMOUR);
            createSimpleEntry(10013, options.MediumanvilId, 46, 285, false, true, 10.0F, false, false, CreationCategories.ARMOUR);
            createSimpleEntry(10013, options.MediumanvilId, 46, 286, false, true, 10.0F, false, false, CreationCategories.ARMOUR);
            createSimpleEntry(10013, options.MediumanvilId, 46, 287, false, true, 10.0F, false, false, CreationCategories.ARMOUR);
            createSimpleEntry(10012, options.MediumanvilId, 205, 288, false, true, 10.0F, false, false, CreationCategories.RESOURCES);
            createSimpleEntry(10012, options.MediumanvilId, 46, 288, false, true, 10.0F, false, false, CreationCategories.RESOURCES);
            createSimpleEntry(10012, options.MediumanvilId, 694, 288, false, true, 10.0F, false, false, CreationCategories.RESOURCES);
            createSimpleEntry(10012, options.MediumanvilId, 837, 288, false, true, 10.0F, false, false, CreationCategories.RESOURCES);
            createSimpleEntry(10012, options.MediumanvilId, 698, 288, false, true, 10.0F, false, false, CreationCategories.RESOURCES);
            createSimpleEntry(10012, options.MediumanvilId, 47, 288, false, true, 10.0F, false, false, CreationCategories.RESOURCES);
            createSimpleEntry(10012, options.MediumanvilId, 223, 288, false, true, 10.0F, false, false, CreationCategories.RESOURCES);
            createSimpleEntry(10012, options.MediumanvilId, 45, 288, false, true, 10.0F, false, false, CreationCategories.RESOURCES);
            createSimpleEntry(10012, options.MediumanvilId, 44, 288, false, true, 10.0F, false, false, CreationCategories.RESOURCES);
            createSimpleEntry(10043, options.MediumanvilId, 205, 326, false, true, 10.0F, false, false, CreationCategories.DECORATION);
            createSimpleEntry(10043, options.MediumanvilId, 46, 326, false, true, 10.0F, false, false, CreationCategories.DECORATION);
            createSimpleEntry(10043, options.MediumanvilId, 47, 326, false, true, 10.0F, false, false, CreationCategories.DECORATION);
            createSimpleEntry(10043, options.MediumanvilId, 223, 326, false, true, 10.0F, false, false, CreationCategories.DECORATION);
            createSimpleEntry(10043, options.MediumanvilId, 45, 326, false, true, 10.0F, false, false, CreationCategories.DECORATION);
            createSimpleEntry(10043, options.MediumanvilId, 44, 326, false, true, 10.0F, false, false, CreationCategories.DECORATION);
            createSimpleEntry(10043, options.MediumanvilId, 694, 326, false, true, 10.0F, false, false, CreationCategories.DECORATION);
            createSimpleEntry(10043, options.MediumanvilId, 837, 326, false, true, 10.0F, false, false, CreationCategories.DECORATION);
            createSimpleEntry(10043, options.MediumanvilId, 698, 326, false, true, 10.0F, false, false, CreationCategories.DECORATION);
            createSimpleEntry(10015, options.MediumanvilId, 46, 135, false, true, 0.0F, false, false, CreationCategories.LIGHTS_AND_LAMPS);
            createSimpleEntry(10015, options.MediumanvilId, 46, 497, false, true, 0.0F, false, false, CreationCategories.LIGHTS_AND_LAMPS);
            createSimpleEntry(10015, options.MediumanvilId, 221, 497, false, true, 0.0F, false, false, CreationCategories.LIGHTS_AND_LAMPS);
            createSimpleEntry(10015, options.MediumanvilId, 46, 675, false, true, 0.0F, false, false, CreationCategories.LIGHTS_AND_LAMPS);
            createSimpleEntry(10015, options.MediumanvilId, 46, 660, false, true, 0.0F, false, false, CreationCategories.LIGHTS_AND_LAMPS);
            createSimpleEntry(10015, options.MediumanvilId, 47, 674, false, true, 0.0F, false, false, CreationCategories.LIGHTS_AND_LAMPS);
            createSimpleEntry(10015, options.MediumanvilId, 223, 674, false, true, 0.0F, false, false, CreationCategories.LIGHTS_AND_LAMPS);
            createSimpleEntry(10015, options.MediumanvilId, 221, 674, false, true, 0.0F, false, false, CreationCategories.LIGHTS_AND_LAMPS);
            createSimpleEntry(10015, options.MediumanvilId, 44, 674, false, true, 0.0F, false, false, CreationCategories.LIGHTS_AND_LAMPS);
            createSimpleEntry(10015, options.MediumanvilId, 45, 674, false, true, 0.0F, false, false, CreationCategories.LIGHTS_AND_LAMPS);
            createSimpleEntry(10014, options.MediumanvilId, 46, 86, false, true, 0.0F, false, false, CreationCategories.SHIELDS);
            createSimpleEntry(10014, options.MediumanvilId, 46, 4, false, true, 0.0F, false, false, CreationCategories.SHIELDS);
            createSimpleEntry(10014, options.MediumanvilId, 46, 83, false, true, 0.0F, false, false, CreationCategories.SHIELDS);
            createSimpleEntry(10014, options.MediumanvilId, 698, 86, false, true, 0.0F, false, false, CreationCategories.SHIELDS);
            createSimpleEntry(10014, options.MediumanvilId, 698, 4, false, true, 0.0F, false, false, CreationCategories.SHIELDS);
            createSimpleEntry(10014, options.MediumanvilId, 698, 83, false, true, 0.0F, false, false, CreationCategories.SHIELDS);
            createSimpleEntry(10014, options.MediumanvilId, 205, 86, false, true, 0.0F, false, false, CreationCategories.SHIELDS);
            createSimpleEntry(10014, options.MediumanvilId, 205, 4, false, true, 0.0F, false, false, CreationCategories.SHIELDS);
            createSimpleEntry(10014, options.MediumanvilId, 205, 83, false, true, 0.0F, false, false, CreationCategories.SHIELDS);
            createSimpleEntry(10014, options.MediumanvilId, 694, 86, false, true, 0.0F, false, false, CreationCategories.SHIELDS);
            createSimpleEntry(10014, options.MediumanvilId, 694, 4, false, true, 0.0F, false, false, CreationCategories.SHIELDS);
            createSimpleEntry(10014, options.MediumanvilId, 694, 83, false, true, 0.0F, false, false, CreationCategories.SHIELDS);
            createSimpleEntry(10014, options.MediumanvilId, 837, 86, false, true, 0.0F, false, false, CreationCategories.SHIELDS);
            createSimpleEntry(10014, options.MediumanvilId, 837, 4, false, true, 0.0F, false, false, CreationCategories.SHIELDS);
            createSimpleEntry(10014, options.MediumanvilId, 837, 83, false, true, 0.0F, false, false, CreationCategories.SHIELDS);
            createSimpleEntry(10015, options.MediumanvilId, 46, 121, false, true, 0.0F, false, false, CreationCategories.TOOL_PARTS);
            createSimpleEntry(10015, options.MediumanvilId, 205, 121, false, true, 0.0F, false, false, CreationCategories.TOOL_PARTS);
            createSimpleEntry(10015, options.MediumanvilId, 698, 121, false, true, 0.0F, false, false, CreationCategories.TOOL_PARTS);
            createSimpleEntry(10015, options.MediumanvilId, 694, 121, false, true, 0.0F, false, false, CreationCategories.TOOL_PARTS);
            createSimpleEntry(10015, options.MediumanvilId, 837, 121, false, true, 0.0F, false, false, CreationCategories.TOOL_PARTS);
            createSimpleEntry(10034, options.MediumanvilId, 46, 252, false, true, 0.0F, false, false, CreationCategories.LOCKS);
            createSimpleEntry(10034, options.MediumanvilId, 46, 568, false, true, 0.0F, false, false, CreationCategories.LOCKS);
            createSimpleEntry(10015, options.MediumanvilId, 49, 547, false, true, 0.0F, false, true, CreationCategories.SHIPBUILDING);
            createSimpleEntry(10015, options.MediumanvilId, 205, 1115, false, true, 0.0F, false, false, CreationCategories.TOOLS);
        }
        // small anvil recipes
        createSimpleEntry(10015, options.MediumanvilId, 47, 772, false, true, 0.0F, false, false, CreationCategories.CONSTRUCTION_MATERIAL);
        createSimpleEntry(10015, options.MediumanvilId, 46, 773, false, true, 0.0F, false, false, CreationCategories.CONSTRUCTION_MATERIAL);
        createSimpleEntry(10015, options.MediumanvilId, 220, 1298, false, true, 0.0F, false, false, CreationCategories.CONSTRUCTION_MATERIAL);
        createSimpleEntry(10015, options.MediumanvilId, 49, 1299, false, true, 0.0F, false, false, CreationCategories.CONSTRUCTION_MATERIAL);
        createSimpleEntry(10015, options.MediumanvilId, 205, 597, false, true, 0.0F, false, false, CreationCategories.CONSTRUCTION_MATERIAL);
        createSimpleEntry(10015, options.MediumanvilId, 44, 599, false, true, 0.0F, false, false, CreationCategories.CONSTRUCTION_MATERIAL);
        createSimpleEntry(10015, options.MediumanvilId, 45, 598, false, true, 0.0F, false, false, CreationCategories.CONSTRUCTION_MATERIAL);
        createSimpleEntry(10010, options.MediumanvilId, 45, 793, false, true, 0.0F, false, false, CreationCategories.TOOL_PARTS);
        createSimpleEntry(10015, options.MediumanvilId, 46, 217, false, true, 0.0F, false, false, CreationCategories.CONSTRUCTION_MATERIAL);
        createSimpleEntry(10015, options.MediumanvilId, 46, 218, false, true, 0.0F, false, false, CreationCategories.CONSTRUCTION_MATERIAL);
        createSimpleEntry(10043, options.MediumanvilId, 44, 227, false, true, 0.0F, false, false, CreationCategories.STATUETTES);
        createSimpleEntry(10043, options.MediumanvilId, 45, 227, false, true, 0.0F, false, false, CreationCategories.STATUETTES);
        createSimpleEntry(10043, options.MediumanvilId, 1411, 227, false, true, 0.0F, false, false, CreationCategories.STATUETTES);
        createSimpleEntry(10043, options.MediumanvilId, 44, 505, false, true, 0.0F, false, false, CreationCategories.STATUETTES);
        createSimpleEntry(10043, options.MediumanvilId, 45, 505, false, true, 0.0F, false, false, CreationCategories.STATUETTES);
        createSimpleEntry(10043, options.MediumanvilId, 1411, 505, false, true, 0.0F, false, false, CreationCategories.STATUETTES);
        createSimpleEntry(10043, options.MediumanvilId, 44, 506, false, true, 0.0F, false, false, CreationCategories.STATUETTES);
        createSimpleEntry(10043, options.MediumanvilId, 45, 506, false, true, 0.0F, false, false, CreationCategories.STATUETTES);
        createSimpleEntry(10043, options.MediumanvilId, 1411, 506, false, true, 0.0F, false, false, CreationCategories.STATUETTES);
        createSimpleEntry(10043, options.MediumanvilId, 44, 507, false, true, 0.0F, false, false, CreationCategories.STATUETTES);
        createSimpleEntry(10043, options.MediumanvilId, 45, 507, false, true, 0.0F, false, false, CreationCategories.STATUETTES);
        createSimpleEntry(10043, options.MediumanvilId, 1411, 507, false, true, 0.0F, false, false, CreationCategories.STATUETTES);
        createSimpleEntry(10043, options.MediumanvilId, 44, 508, false, true, 0.0F, false, false, CreationCategories.STATUETTES);
        createSimpleEntry(10043, options.MediumanvilId, 45, 508, false, true, 0.0F, false, false, CreationCategories.STATUETTES);
        createSimpleEntry(10043, options.MediumanvilId, 1411, 508, false, true, 0.0F, false, false, CreationCategories.STATUETTES);
        createSimpleEntry(10043, options.MediumanvilId, 44, 230, false, true, 0.0F, false, false, CreationCategories.JEWELRY);
        createSimpleEntry(10043, options.MediumanvilId, 45, 230, false, true, 0.0F, false, false, CreationCategories.JEWELRY);
        createSimpleEntry(10043, options.MediumanvilId, 1411, 230, false, true, 0.0F, false, false, CreationCategories.JEWELRY);
        createSimpleEntry(10043, options.MediumanvilId, 44, 231, false, true, 0.0F, false, false, CreationCategories.JEWELRY);
        createSimpleEntry(10043, options.MediumanvilId, 45, 231, false, true, 0.0F, false, false, CreationCategories.JEWELRY);
        createSimpleEntry(10043, options.MediumanvilId, 1411, 231, false, true, 0.0F, false, false, CreationCategories.JEWELRY);
        createSimpleEntry(10043, options.MediumanvilId, 694, 231, false, true, 0.0F, false, false, CreationCategories.JEWELRY);
        createSimpleEntry(10043, options.MediumanvilId, 837, 231, false, true, 0.0F, false, false, CreationCategories.JEWELRY);
        createSimpleEntry(10043, options.MediumanvilId, 698, 231, false, true, 0.0F, false, false, CreationCategories.JEWELRY);
        createSimpleEntry(10043, options.MediumanvilId, 44, 297, false, true, 100.0F, false, false, CreationCategories.JEWELRY);
        createSimpleEntry(10043, options.MediumanvilId, 45, 297, false, true, 100.0F, false, false, CreationCategories.JEWELRY);
        createSimpleEntry(10043, options.MediumanvilId, 1411, 297, false, true, 100.0F, false, false, CreationCategories.JEWELRY);
        createSimpleEntry(10043, options.MediumanvilId, 698, 297, false, true, 100.0F, false, false, CreationCategories.JEWELRY);
        createSimpleEntry(10043, options.MediumanvilId, 694, 297, false, true, 100.0F, false, false, CreationCategories.JEWELRY);
        createSimpleEntry(10043, options.MediumanvilId, 837, 297, false, true, 100.0F, false, false, CreationCategories.JEWELRY);
        createSimpleEntry(10015, options.MediumanvilId, 221, 902, false, true, 0.0F, false, false, CreationCategories.TOOL_PARTS);
        createSimpleEntry(10015, options.MediumanvilId, 223, 904, false, true, 0.0F, false, false, CreationCategories.TOOL_PARTS);
        createSimpleEntry(10015, options.MediumanvilId, 220, 1166, false, true, 0.0F, false, false, CreationCategories.TOOLS);
        createSimpleEntry(10011, options.MediumanvilId, 46, 1126, false, true, 10.0F, false, false, CreationCategories.WEAPON_HEADS);
        createSimpleEntry(10043, options.MediumanvilId, 205, 1369, false, true, 10.0F, false, false, CreationCategories.TOOL_PARTS);
        createSimpleEntry(10043, options.MediumanvilId, 837, 1369, false, true, 10.0F, false, false, CreationCategories.TOOL_PARTS);
        createSimpleEntry(10043, options.MediumanvilId, 694, 1369, false, true, 10.0F, false, false, CreationCategories.TOOL_PARTS);
        createSimpleEntry(10043, options.MediumanvilId, 698, 1369, false, true, 10.0F, false, false, CreationCategories.TOOL_PARTS);

        AdvancedCreationEntry washingBowl = createAdvancedEntry(10015, options.MediumanvilId, 221, 895, false, true, 0.0F, false, true, 0, 30.0, CreationCategories.FURNITURE);
        washingBowl.setDepleteFromTarget(1500);
        washingBowl.addRequirement(new CreationRequirement(1, 897, 3, true));
        washingBowl.addRequirement(new CreationRequirement(2, 77, 1, true));

        createAdvancedMetalicEntry(10015, options.MediumanvilId, 220, 1341, false, true, 0.0F, false, false, CreationCategories.TOOLS, new CreationRequirement(1, 790, 3, true), new CreationRequirement(2, 100, 1, true));

        createMetallicEntries(10043, options.MediumanvilId, 46, 1345, false, true, 0.0F, false, false, CreationCategories.TOOLS);
        createMetallicEntries(10015, options.MediumanvilId, 46, 1357, false, true, 1000.0F, false, false, CreationCategories.TOOL_PARTS);
        createMetallicEntries(10043, options.MediumanvilId, 46, 1368, false, true, 10.0F, false, false, CreationCategories.TOOL_PARTS);
        // large anvil recipes
        createSimpleEntry(10015, options.MediumanvilId, 46, 681, false, true, 0.0F, false, false, CreationCategories.CONSTRUCTION_MATERIAL);
        createSimpleEntry(10015, options.MediumanvilId, 47, 838, false, true, 0.0F, false, false, 20, 30.0, CreationCategories.CONSTRUCTION_MATERIAL);
        createSimpleEntry(10015, options.MediumanvilId, 205, 582, false, true, 0.0F, false, false, CreationCategories.TOOL_PARTS);
        createSimpleEntry(10013, options.MediumanvilId, 372, 478, false, true, 0.0F, false, false, CreationCategories.ARMOUR);
        createSimpleEntry(10013, options.MediumanvilId, 372, 474, false, true, 0.0F, false, false, CreationCategories.ARMOUR);
        createSimpleEntry(10013, options.MediumanvilId, 372, 475, false, true, 0.0F, false, false, CreationCategories.ARMOUR);
        createSimpleEntry(10013, options.MediumanvilId, 372, 476, false, true, 0.0F, false, false, CreationCategories.ARMOUR);
        createSimpleEntry(10013, options.MediumanvilId, 372, 477, false, true, 0.0F, false, false, CreationCategories.ARMOUR);
        createSimpleEntry(10012, options.MediumanvilId, 288, 274, false, true, 10.0F, false, false, CreationCategories.ARMOUR);
        createSimpleEntry(10012, options.MediumanvilId, 288, 279, false, true, 10.0F, false, false, CreationCategories.ARMOUR);
        createSimpleEntry(10012, options.MediumanvilId, 288, 278, false, true, 10.0F, false, false, CreationCategories.ARMOUR);
        createSimpleEntry(10012, options.MediumanvilId, 288, 275, false, true, 10.0F, false, false, CreationCategories.ARMOUR);
        createSimpleEntry(10012, options.MediumanvilId, 288, 276, false, true, 10.0F, false, false, CreationCategories.ARMOUR);
        createSimpleEntry(10012, options.MediumanvilId, 288, 277, false, true, 10.0F, false, false, CreationCategories.ARMOUR);
        createSimpleEntry(10012, options.MediumanvilId, 288, 703, false, true, 10.0F, false, false, CreationCategories.ANIMAL_EQUIPMENT);
        createSimpleEntry(10015, options.MediumanvilId, 205, 609, false, true, 0.0F, false, false, CreationCategories.CONSTRUCTION_MATERIAL);
        createSimpleEntry(10015, options.MediumanvilId, 221, 136, false, true, 0.0F, false, false, CreationCategories.LIGHTS_AND_LAMPS);
        createSimpleEntry(10015, options.MediumanvilId, 46, 188, false, true, 0.0F, false, false, CreationCategories.CONSTRUCTION_MATERIAL);
        createSimpleEntry(10043, options.MediumanvilId, 47, 839, false, true, 0.0F, false, false, 20, 30.0, CreationCategories.CONSTRUCTION_MATERIAL);
        createSimpleEntry(10043, options.MediumanvilId, 44, 840, false, true, 0.0F, false, false, 20, 30.0, CreationCategories.CONSTRUCTION_MATERIAL);
        createSimpleEntry(10043, options.MediumanvilId, 45, 325, false, true, 0.0F, false, true, CreationCategories.ALTAR);
        createSimpleEntry(10043, options.MediumanvilId, 44, 324, false, true, 0.0F, false, true, CreationCategories.ALTAR);
        createSimpleEntry(10015, options.MediumanvilId, 46, 859, false, true, 0.0F, false, false, CreationCategories.CONSTRUCTION_MATERIAL);
        createSimpleEntry(10015, options.MediumanvilId, 221, 897, false, true, 0.0F, false, false, CreationCategories.CONSTRUCTION_MATERIAL);
    }
}
